import { imageManifest } from '../assets/imageManifest.js'

const q = {
  best: 'best',
  acceptable: 'acceptable',
  risky: 'risky',
}

function choice(id, label, text, quality, next, risk, meters, consequence) {
  return { id, label, text, quality, next, risk, meters, consequence }
}

export const scenarios = [
  {
    id: 'vdl',
    title: 'VDL Groep',
    year: '2021',
    sector: 'Maakindustrie / Automotive',
    role: 'Operationeel directeur VDL Nedcar',
    cia: ['Availability'],
    category: ['proces', 'tech'],
    tbkLens: 'Productiecontinuiteit',
    accent: '#ff8c00',
    image: imageManifest.vdl,
    sources: ['NOS', 'Omroep Brabant', 'Maakindustrie Nieuws'],
    collapse: {
      title: 'Productiecrisis buiten controle',
      text: 'De combinatie van verspreiding, klantonzekerheid, ketendruk en zwak herstelvermogen is te groot geworden. De board neemt de regie over, productie blijft stil en klanten schakelen noodleveranciers in.',
    },
    intro: [
      'Donderdag 03:47. De nachtdienst belt: systemen vallen een voor een uit. Om 06:00 staan medewerkers bij de poort en BMW verwacht onderdelen.',
      'Dit scenario draait om productiecontinuiteit: als digitale planning, voorraad en kwaliteitsregistratie uitvallen, staat niet alleen IT stil maar ook de keten.',
    ],
    impactStats: [
      { value: '15k', label: 'medewerkers wereldwijd' },
      { value: '1 maand', label: 'volledig herstel' },
      { value: 'keten', label: 'klanten en leveranciers geraakt' },
    ],
    reflection: {
      summary: 'VDL laat zien dat een cyberincident in een productiebedrijf direct een bedrijfscontinuiteitsprobleem wordt. Planning, kwaliteit, klantafspraken, leveranciers en herstelvermogen komen tegelijk onder druk.',
      cia: 'De kern is Availability: systemen zijn niet beschikbaar, waardoor productie en ketenafspraken vastlopen. Integrity speelt mee zodra handmatige kwaliteitsdata niet meer betrouwbaar aansluit op digitale registratie.',
      tbk: 'De TBK-bril is productiecontinuiteit: welke processen moeten blijven draaien, welke ketenpartners raken afhankelijk, en welke maatregel verlaagt vooral impact in plaats van alleen kans?',
      questions: [
        'Welk productie- of planningsproces mag in jouw praktijkbedrijf maximaal een dag stilliggen?',
        'Welke klant- of leveranciersafspraak komt direct onder druk als digitale systemen uitvallen?',
        'Zijn back-ups, noodprocedures en handmatige kwaliteitsregistratie echt getest?',
      ],
    },
    nodes: [
      {
        id: 'start',
        title: 'De eerste ochtend',
        tbkTags: ['Productiecontinuiteit', 'Kwaliteitsborging'],
        situation: 'Je weet nog niet of het een storing of aanval is. Enkele systemen lijken nog te werken.',
        question: 'Wat is je eerste managementbeslissing?',
        choices: [
          choice('A', 'Volledig isoleren', 'Leg alle digitale systemen stil en stuur teams naar crisisprocedure.', q.best, 'triage', { proces: 2, tech: 1 }, { operation: 2, reputation: 0, financial: 1, chain: 1, recovery: 1, pressure: 1 }, 'De fabriek valt direct stil. BMW belt binnen tien minuten terug, maar IT meldt dat de besmetting zich niet verder verspreidt. Je verliest productie-uren, maar houdt controle over de grens van het incident.'),
          choice('B', 'Handmatig doorwerken', 'Laat teams zonder digitale afhankelijkheid op papier verder werken.', q.acceptable, 'quality', { proces: 2, tech: 0 }, { operation: 2, reputation: 0, financial: 1, legal: 1, chain: 1, trust: 1, recovery: -1, pressure: 2 }, 'Een deel van de productie komt op gang. Op de vloer voelt dat als winst, maar het tempo zakt hard: planners bellen rond, teamleiders werken met papieren lijsten en niemand weet zeker of voorraad, kwaliteitsdata en vrijgave nog synchroon lopen.'),
          choice('C', 'Lijn testen', 'Start een productielijn met planning opnieuw op om te zien wat nog werkt.', q.risky, 'spread', { proces: 2, tech: 2 }, { operation: 4, reputation: 1, financial: 2, chain: 2, recovery: -1, pressure: 2 }, 'De lijn start, hapert en valt uit. Daarna melden twee systemen die eerst schoon leken dezelfde foutmelding. De test heeft informatie opgeleverd, maar ook verspreiding veroorzaakt.'),
        ],
      },
      {
        id: 'spread',
        title: 'De test bijt terug',
        tbkTags: ['Incidentrespons', 'Netwerksegmentatie'],
        situation: 'De productielijn die je testte heeft twee extra systemen geraakt. IT wil nu alles loskoppelen, terwijl productie vraagt of de schade al niet is gebeurd.',
        question: 'Hoe herstel je grip na de risicovolle test?',
        choices: [
          choice('A', 'Noodstop accepteren', 'Stop alsnog alles en geef IT mandaat om fysiek te isoleren.', q.best, 'triage', { proces: 2, tech: 1 }, { operation: 2, financial: 1, chain: 1, recovery: 1, pressure: 1 }, 'De tweede stilstand voelt pijnlijker omdat hij later komt. Toch stopt de verspreiding nu wel en kan IT een betrouwbare inventarisatie maken.'),
          choice('B', 'Nog een lijn proberen', 'Test een andere lijn die op een ander segment lijkt te draaien.', q.risky, 'triage', { proces: 2, tech: 2 }, { operation: 4, reputation: 1, financial: 2, chain: 2, recovery: -2, pressure: 2 }, 'De organisatie blijft zoeken naar productie, maar IT verliest het overzicht. Niemand weet meer zeker welke systemen schoon zijn.'),
          choice('C', 'Alleen kantoor-IT uit', 'Laat productie-IT nog kort draaien en sluit vooral kantoor-IT af.', q.risky, 'triage', { proces: 1, tech: 2 }, { operation: 3, reputation: 1, financial: 1, chain: 2, recovery: -1, pressure: 2 }, 'Het onderscheid tussen kantoor en productie blijkt minder hard dan gehoopt. De maatregel klinkt logisch, maar de afhankelijkheden zijn niet goed genoeg bekend.'),
        ],
      },
      {
        id: 'triage',
        title: 'Crisisteam of improvisatie',
        tbkTags: ['Governance', 'Besluitvorming'],
        situation: 'Om 07:20 staan productie, IT, communicatie en sales allemaal aan je bureau. Iedereen vraagt om een ander eerste besluit.',
        question: 'Hoe organiseer je de eerste twee uur?',
        choices: [
          choice('A', 'Crisisteam met mandaat', 'Maak een klein crisisteam: IT isoleert, operations prioriteert, communicatie stemt klantupdates af.', q.best, 'communication', { proces: 2, mens: 0 }, { operation: 0, reputation: 0, financial: 0, recovery: 1, trust: 1, pressure: -1 }, 'De chaos wordt niet opgelost, maar wel geordend. Mensen weten wie beslist en welke informatie elk half uur terugkomt.'),
          choice('B', 'Iedereen eigen spoor', 'Laat elk team doen wat nodig is en verzamel later de status.', q.risky, 'communication', { mens: 1, proces: 2 }, { operation: 2, reputation: 1, chain: 1, pressure: 2 }, 'Teams werken hard, maar langs elkaar heen. Sales belooft klanten meer dan IT kan waarmaken en operations krijgt tegenstrijdige instructies.'),
          choice('C', 'Alle besluiten via directie', 'Laat elke grote beslissing eerst door de directie accorderen.', q.acceptable, 'communication', { proces: 1 }, { operation: 1, reputation: 0, financial: 0, pressure: 2 }, 'Bestuurlijk netjes, maar traag. In een incident is snelheid ook een controlemaatregel.'),
        ],
      },
      {
        id: 'quality',
        title: 'Handmatig zonder traceerbaarheid',
        tbkTags: ['Kwaliteitsborging', 'Klantafspraken'],
        situation: 'BMW accepteert veiligheidsonderdelen alleen met controleerbare kwaliteitsdata.',
        question: 'Hoe houd je operatie en kwaliteit in balans?',
        choices: [
          choice('A', 'Tijdelijke uitzondering vragen', 'Vraag BMW formeel om tijdelijke handmatige documentatie te accepteren.', q.best, 'communication', { proces: 1, mens: 0 }, { operation: 1, reputation: 0, financial: 0, legal: 0, trust: 1, pressure: 0 }, 'BMW waardeert dat je het probleem vroeg benoemt. De uitzondering is niet vanzelfsprekend, en de handmatige registratie blijft trager, maar het gesprek gaat nu over beheersing in plaats van verzwijgen.'),
          choice('B', 'Doorgaan en later herstellen', 'Maak voorraad en vul digitale registratie later aan.', q.acceptable, 'communication', { proces: 2, tech: 0 }, { operation: 2, reputation: 1, financial: 2, legal: 2, chain: 1, recovery: -1, pressure: 2 }, 'De productiehal voelt productief, maar het magazijn vult zich met units die nog niet vrijgegeven kunnen worden. Elke handmatige lijst moet later worden gecontroleerd en ingevoerd. Je wint uren op de vloer en verliest dagen in verificatie.'),
          choice('C', 'Alles alsnog stoppen', 'Stop handmatige productie volledig tot IT hersteld is.', q.acceptable, 'communication', { proces: 0, tech: 0 }, { operation: 2, reputation: 0, financial: 1, chain: 1, recovery: 1, pressure: 1 }, 'Kwaliteit blijft schoon, maar de leverdruk stijgt. Je voorkomt een integriteitsprobleem en vergroot tegelijk de beschikbaarheidsschade.'),
        ],
      },
      {
        id: 'communication',
        title: 'BMW wil zekerheid',
        tbkTags: ['Klantcommunicatie', 'Ketenafhankelijkheid'],
        situation: 'BMW vraagt niet alleen of je vandaag levert, maar wanneer zij hun eigen planning moeten aanpassen. Een te optimistische update kan later duurder zijn dan slecht nieuws.',
        question: 'Wat communiceer je naar de klant?',
        choices: [
          choice('A', 'Conservatief venster', 'Geef een realistisch venster: vandaag geen normale levering, nieuwe update over twee uur.', q.best, 'forensics', { proces: 1, mens: 0 }, { reputation: 0, chain: 1, trust: 1, pressure: -1 }, 'BMW is niet blij, maar kan zelf sturen. Je bouwt vertrouwen door onzekerheid expliciet te maken.'),
          choice('B', 'Optimistische belofte', 'Zeg dat je waarschijnlijk vanmiddag deels kunt leveren.', q.risky, 'forensics', { mens: 1, proces: 1 }, { reputation: 2, chain: 2, financial: 1, pressure: 1, trust: -1 }, 'De klant houdt capaciteit vrij op basis van jouw hoop. Als herstel langer duurt, wordt jouw communicatie onderdeel van de schade.'),
          choice('C', 'Geen externe update', 'Wacht tot IT exact weet wat er aan de hand is.', q.acceptable, 'forensics', { proces: 1 }, { reputation: 1, chain: 1, pressure: 1 }, 'Je voorkomt speculatie, maar klanten gaan zelf aannames maken. In een keten is stilte ook informatie.'),
        ],
      },
      {
        id: 'forensics',
        title: 'Bewijs of snelheid',
        tbkTags: ['Forensisch onderzoek', 'Herstelvermogen'],
        situation: 'Een externe securitypartij adviseert om logs en schijfbeelden veilig te stellen voordat systemen worden teruggezet. Operations wil vooral weer draaien.',
        question: 'Wat krijgt voorrang?',
        choices: [
          choice('A', 'Bewijs veiligstellen', 'Bevries kritieke systemen kort voor forensisch onderzoek en herstel daarna gefaseerd.', q.best, 'backup', { proces: 1, tech: 1 }, { operation: 1, legal: 0, recovery: 1, pressure: 0 }, 'Herstel start iets later, maar je behoudt zicht op oorzaak, meldplichten en herbesmettingsrisico.'),
          choice('B', 'Meteen terugzetten', 'Zet systemen zo snel mogelijk terug zonder uitgebreid onderzoek.', q.risky, 'backup', { proces: 1, tech: 2 }, { operation: 1, legal: 2, recovery: -1, pressure: 1 }, 'Je wint uren, maar verliest bewijs. Als dezelfde ingang open blijft, kan herstel schijnveilig zijn.'),
          choice('C', 'Alleen belangrijkste logs', 'Bewaar minimale logs en start parallel herstel.', q.acceptable, 'backup', { proces: 1, tech: 1 }, { operation: 1, legal: 1, recovery: 0 }, 'Een pragmatische middenweg. Je hebt minder bewijs, maar houdt het bedrijf in beweging.'),
        ],
      },
      {
        id: 'backup',
        title: 'Back-ups blijken ongelijk',
        tbkTags: ['Back-ups', 'Herstelstrategie'],
        situation: 'Back-ups zijn beschikbaar, maar niet allemaal even recent. Productieplanning is drie dagen oud; voorraaddata is van vannacht; kwaliteitsdata is deels onzeker.',
        question: 'Welke herstelvolgorde kies je?',
        choices: [
          choice('A', 'Kritieke ketenprocessen eerst', 'Herstel planning, voorraad en klantcommunicatie voor je volledige kantoor-IT terugzet.', q.best, 'ransom', { proces: 1, tech: 1 }, { operation: 0, chain: 0, recovery: 2, trust: 1 }, 'De fabriek draait nog niet normaal, maar de keten krijgt weer betrouwbare informatie. Herstelvermogen stijgt.'),
          choice('B', 'Alles tegelijk', 'Start herstel van alle systemen tegelijk om tijd te winnen.', q.risky, 'ransom', { proces: 2, tech: 1 }, { operation: 2, chain: 1, recovery: -1, pressure: 2 }, 'Teams zitten elkaar in de weg. Er ontstaan wachtrijen, versies botsen en niemand weet welk systeem leidend is.'),
          choice('C', 'Kantoor-IT eerst', 'Herstel mail en kantoorapplicaties zodat mensen weer kunnen werken.', q.acceptable, 'ransom', { proces: 1 }, { operation: 1, chain: 1, recovery: 0 }, 'Communicatie wordt makkelijker, maar productieplanning blijft de bottleneck.'),
        ],
      },
      {
        id: 'ransom',
        title: 'De losgeldvraag',
        tbkTags: ['Herstelvermogen', 'Governance'],
        situation: 'Ransomware eist betaling. Back-ups bestaan, maar zijn niet allemaal actueel.',
        question: 'Welke keuze past het best bij herstelvermogen?',
        choices: [
          choice('A', 'Herstellen via back-ups', 'Niet betalen; herstel via back-ups en accepteer dat recente data opnieuw moet.', q.best, 'supplier', { proces: 1, tech: 1 }, { operation: 1, reputation: 0, financial: 1, recovery: 1, trust: 1 }, 'Herstel duurt langer, maar het bedrijf beloont criminelen niet. De keuze is uitlegbaar aan klanten, politie en verzekeraar.'),
          choice('B', 'Betalen', 'Betaal omdat stilstand per dag duurder lijkt dan losgeld.', q.risky, 'supplier', { mens: 1, proces: 2, tech: 1 }, { operation: 2, reputation: 2, financial: 2, legal: 1, recovery: -1, trust: -1 }, 'De sleutel werkt maar gedeeltelijk. Twee systemen blijven stuk en de vraag ontstaat of je criminelen hebt beloond zonder echte controle terug te kopen.'),
          choice('C', 'Onderhandelen', 'Probeer tijd te winnen terwijl IT alternatieven onderzoekt.', q.acceptable, 'supplier', { proces: 1, tech: 0 }, { operation: 1, reputation: 1, financial: 1, pressure: 1 }, 'Je wint tijd, maar de klok blijft lopen. Het crisisteam gebruikt de onderhandeling vooral om back-upherstel verder te testen.'),
        ],
      },
      {
        id: 'supplier',
        title: 'Leveranciers bellen mee',
        tbkTags: ['Ketenafhankelijkheid', 'Leveranciersmanagement'],
        situation: 'Niet alleen BMW belt. Ook een leverancier van kritieke componenten wil weten of zij hun eigen productie moeten aanpassen.',
        question: 'Hoe betrek je leveranciers in de crisis?',
        choices: [
          choice('A', 'Ketenupdate organiseren', 'Stuur vaste updates naar kritieke klanten en leveranciers met scenario, impact en volgende update.', q.best, 'restart', { proces: 2 }, { reputation: 0, chain: 0, trust: 1, pressure: -1 }, 'De keten krijgt een ritme. Niemand heeft volledige zekerheid, maar partners kunnen plannen op basis van dezelfde informatie.'),
          choice('B', 'Alleen grootste klant', 'Richt alle communicatie op BMW en laat kleinere ketenpartners wachten.', q.acceptable, 'restart', { proces: 1, mens: 1 }, { reputation: 1, chain: 1, trust: -1 }, 'Commercieel begrijpelijk, maar kleinere partners krijgen onzekerheid doorgeschoven. Dat kan later alsnog terugkomen.'),
          choice('C', 'Niets delen buiten contract', 'Deel alleen informatie als contractueel verplicht.', q.risky, 'restart', { proces: 2 }, { reputation: 2, chain: 2, legal: 1, trust: -2 }, 'Juridisch voorzichtig, maar operationeel schadelijk. Partners gaan eigen noodscenario\'s activeren zonder jouw input.'),
        ],
      },
      {
        id: 'restart',
        title: 'Gefaseerd herstarten',
        tbkTags: ['Herstartplanning', 'Kwaliteitsborging'],
        situation: 'Na dagen herstel kan een deel van de productie terugkomen. Niet alles tegelijk: de herstart moet veilig, controleerbaar en uitlegbaar zijn.',
        question: 'Welke herstartstrategie kies je?',
        choices: [
          choice('A', 'Een gecontroleerde lijn', 'Start een lijn met volledige kwaliteitscontrole en monitoring.', q.best, 'customer', { proces: 1, tech: 1 }, { operation: 0, financial: 1, recovery: 1, trust: 1 }, 'De output is beperkt, maar betrouwbaar. De eerste succesvolle batch wordt een bewijs dat herstel werkt.'),
          choice('B', 'Maximale capaciteit', 'Start zoveel mogelijk lijnen tegelijk om achterstand in te lopen.', q.risky, 'customer', { proces: 2, tech: 1 }, { operation: 2, reputation: 1, financial: 1, recovery: -1, pressure: 2 }, 'De achterstand lijkt kleiner te worden, maar storingen en kwaliteitsvragen stapelen zich op. Herstel wordt opnieuw chaotisch.'),
          choice('C', 'Alleen kantoorprocessen', 'Laat productie nog wachten en herstel eerst administratie en rapportage.', q.acceptable, 'customer', { proces: 1 }, { operation: 2, financial: 1, recovery: 0 }, 'Bestuurlijke controle verbetert, maar de fabriek blijft het echte knelpunt.'),
        ],
      },
      {
        id: 'customer',
        title: 'Contractboetes en vertrouwen',
        tbkTags: ['Klantafspraken', 'Financieel risico'],
        situation: 'BMW accepteert vertraging niet onbeperkt. De juridische afdeling wijst op contractboetes, sales op verlies van vertrouwen.',
        question: 'Waar stuur je op in het klantgesprek?',
        choices: [
          choice('A', 'Gezamenlijk herstelplan', 'Bespreek leverprioriteiten, tijdelijke afwijkingen en dagelijkse updatepunten met BMW.', q.best, 'board', { proces: 2, mens: 0 }, { financial: 1, reputation: 0, chain: 0, trust: 1 }, 'De klant ziet dat je niet alleen sorry zegt, maar stuurt op continuiteit. Boetes verdwijnen niet, maar vertrouwen blijft werkbaar.'),
          choice('B', 'Juridisch afschermen', 'Laat alle communicatie via legal lopen om aansprakelijkheid te beperken.', q.acceptable, 'board', { proces: 1 }, { legal: 0, reputation: 1, chain: 1, trust: -1 }, 'Je beperkt losse uitspraken, maar het gesprek wordt kouder. De klant mist operationele duidelijkheid.'),
          choice('C', 'Commerciele korting beloven', 'Bied korting aan om de relatie snel te redden.', q.risky, 'board', { mens: 1, proces: 1 }, { financial: 2, reputation: 1, chain: 0, pressure: 1 }, 'De korting koopt goodwill, maar lost planning, kwaliteit en herstel niet op. Je betaalt voor vertrouwen zonder oorzaak aan te pakken.'),
        ],
      },
      {
        id: 'board',
        title: 'De board wil een les',
        tbkTags: ['Governance', 'Risicomanagement'],
        situation: 'Een maand later vraagt de board om drie lessen: wat was de ingang, waarom werd impact zo groot, en hoe voorkomen we herhaling?',
        question: 'Welke analyse is het sterkst?',
        choices: [
          choice('A', 'Kans en impact scheiden', 'MFA verlaagt kans; segmentatie en back-ups verlagen impact en hersteltijd.', q.best, 'lesson', { proces: 2, tech: 1 }, { recovery: 2, trust: 1 }, 'De board krijgt geen losse maatregel, maar een risicodenkkader. Dat maakt investeringen beter te prioriteren.'),
          choice('B', 'Een technische oorzaak', 'Noem vooral malware en kwetsbare systemen als oorzaak.', q.acceptable, 'lesson', { tech: 1, proces: 1 }, { recovery: 0 }, 'Niet onwaar, maar te smal. De bedrijfsschade kwam ook door ketenafhankelijkheid, kwaliteit en besluitvorming.'),
          choice('C', 'Menselijke fout aanwijzen', 'Leg de nadruk op medewerkers die mogelijk verkeerd klikten.', q.risky, 'lesson', { mens: 2, proces: 1 }, { reputation: 1, trust: -1, recovery: -1 }, 'De analyse zoekt schuld in plaats van systeemverbetering. Daardoor blijven proces- en herstelzwaktes onderbelicht.'),
        ],
      },
      {
        id: 'lesson',
        title: 'Structurele les',
        tbkTags: ['Toegangsbeheer', 'Netwerksegmentatie'],
        situation: 'De board wil weten welke maatregel de grootste structurele winst geeft.',
        question: 'Welke maatregel prioriteer je?',
        choices: [
          choice('A', 'MFA + segmentatie + back-up-test', 'Combineer ingang voorkomen, verspreiding beperken en herstel oefenen.', q.best, 'end_scenario', { mens: 0, proces: 2, tech: 2 }, { recovery: 2, trust: 1 }, 'De maatregelenset past bij risico = kans x impact. MFA verkleint de kans, segmentatie beperkt impact en geteste back-ups verkorten herstel.'),
          choice('B', 'Alleen netwerksegmentatie', 'Scheid kantoor-IT en productie-IT hard van elkaar.', q.acceptable, 'end_scenario', { proces: 1, tech: 1 }, { recovery: 1 }, 'Sterk voor schadebeperking, vooral als een aanval al binnen is. Als enige maatregel laat het de ingang en hersteltest nog open.'),
          choice('C', 'Alleen extra training', 'Train medewerkers en communiceer scherper over phishing.', q.risky, 'end_scenario', { mens: 1, proces: 1, tech: 1 }, { operation: 1, reputation: 0, financial: 0, recovery: -1 }, 'Nuttig, maar te smal. Mensen maken fouten; goede processen en systemen zorgen dat een fout geen fabriek stillegt.'),
        ],
      },
    ],
  },
  {
    id: 'maersk',
    title: 'Maersk / NotPetya',
    year: '2017',
    sector: 'Logistiek / Supply chain',
    role: 'Head of Operations APM Terminals Rotterdam',
    cia: ['Availability'],
    category: ['tech', 'proces'],
    tbkLens: 'Ketenafhankelijkheid',
    accent: '#00d4ff',
    image: imageManifest.maersk,
    sources: ['Wired', 'The Register', 'NOS'],
    intro: [
      'De Rotterdamse terminal valt stil. Zonder containervolgingssysteem weet niemand welke container waar staat of wat ermee mag gebeuren.',
      'Dit scenario draait om ketenafhankelijkheid: een software-update elders in de wereld kan fysieke goederenstromen in Rotterdam stilleggen.',
    ],
    impactStats: [
      { value: '76', label: 'terminals geraakt' },
      { value: '$300M', label: 'geschatte schade' },
      { value: '45k', label: 'computers hersteld' },
    ],
    nodes: [
      {
        id: 'start',
        title: 'Terminal open of dicht',
        tbkTags: ['Logistiek', 'Veiligheid', 'Ketenafhankelijkheid'],
        situation: 'Vijf schepen wachten. Zonder systeem is gevaarlijke lading niet betrouwbaar te lokaliseren.',
        question: 'Wat doe je met de terminal?',
        choices: [
          choice('A', 'Sluit de terminal', 'Stop de operatie tot duidelijk is wat veilig kan.', q.best, 'priority', { proces: 2, tech: 1 }, { operation: 2, reputation: 0, financial: 1, chain: 1, recovery: 1, pressure: 1 }, 'Schepen worden omgeleid en wachttijden lopen op, maar gevaarlijke lading blijft traceerbaar. Je koopt tijd om de operatie gecontroleerd kleiner te maken in plaats van blind door te draaien.'),
          choice('B', 'Alles handmatig', 'Laat teams met manifesten en Excel doorwerken.', q.risky, 'priority', { proces: 2, tech: 1 }, { operation: 3, reputation: 2, financial: 2, legal: 1, chain: 2, recovery: -1, pressure: 2 }, 'De kade lijkt weer te bewegen, maar er ontstaan verschillende versies van de waarheid. Douane, planners en vervoerders werken met andere lijsten, waardoor herstel later begint met reconciliatie in plaats van doorstroming.'),
          choice('C', 'Alleen veilige lading', 'Accepteer tijdelijk alleen niet-gevaarlijke lading.', q.acceptable, 'priority', { proces: 1, tech: 1 }, { operation: 2, reputation: 0, financial: 1, chain: 1, recovery: 0, pressure: 1 }, 'Een deel van de terminal blijft bruikbaar, maar capaciteit wordt schaars. Klanten met gevaarlijke of tijdkritische lading moeten omplannen en je team moet scherp bewaken dat uitzonderingen niet alsnog door de poort glippen.'),
        ],
      },
      {
        id: 'priority',
        title: 'Beperkte capaciteit',
        tbkTags: ['Prioriteren', 'Business continuity'],
        situation: 'Handmatig kan maar een deel van de operatie draaien.',
        question: 'Welke lading krijgt prioriteit?',
        choices: [
          choice('A', 'Kritieke lading eerst', 'Medische, bederfelijke en veiligheidskritieke lading krijgen voorrang.', q.best, 'recovery', { proces: 1, mens: 0 }, { operation: 0, reputation: 0, financial: 0 }, 'Capaciteit wordt gekoppeld aan maatschappelijke en operationele impact.'),
          choice('B', 'Hardste klant eerst', 'Geef voorrang aan klanten die escaleren.', q.risky, 'recovery', { mens: 1, proces: 2 }, { operation: 2, reputation: 2, financial: 1, chain: 2, trust: -1, pressure: 2 }, 'Je beloont druk in plaats van impact. Stille maar kritieke zendingen blijven liggen, waardoor later nieuwe escalaties ontstaan bij klanten die juist afhankelijk waren van voorspelbare prioritering.'),
          choice('C', 'First-in-first-out', 'Volg de normale volgorde ondanks het incident.', q.acceptable, 'recovery', { proces: 1, tech: 0 }, { operation: 1, reputation: 1, financial: 1, chain: 1, pressure: 1 }, 'Het voelt eerlijk en uitlegbaar, maar het incident is geen normale wachtrij. Medische, bederfelijke of veiligheidskritieke lading kan achter minder urgente containers blijven steken.'),
        ],
      },
      {
        id: 'recovery',
        title: 'Ghana-server',
        tbkTags: ['Herstelvermogen', 'Globale operatie'],
        situation: 'Een offline server in Ghana bevat de enige bruikbare kopie van cruciale netwerkdata.',
        question: 'Wat prioriteer je?',
        choices: [
          choice('A', 'Globaal herstel', 'Begin wereldwijd herstel zodra de data beschikbaar is.', q.best, 'lesson', { proces: 1, tech: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Het hele netwerk komt sneller terug.'),
          choice('B', 'Rotterdam eerst', 'Wacht op een lokale kopie zodat Rotterdam sneller herstelt.', q.acceptable, 'lesson', { proces: 1, tech: 0 }, { operation: 1, reputation: 1, financial: 1, chain: 2, recovery: -1, pressure: 1 }, 'Lokaal aantrekkelijk, maar de keten herstelt niet per haven. Andere terminals blijven wachten op dezelfde netwerkdata en Rotterdam krijgt later alsnog terugslag van wereldwijde vertraging.'),
        ],
      },
      {
        id: 'lesson',
        title: 'Structurele zwakte',
        tbkTags: ['Netwerksegmentatie', 'Supply chain'],
        situation: 'De aanval begon via software, maar de wereldwijde schade kwam door snelle verspreiding.',
        question: 'Welke zwakte maakte de schade zo groot?',
        choices: [
          choice('A', 'Geen segmentatie', 'Een besmet kantoor kon het wereldwijde netwerk raken.', q.best, 'end_scenario', { tech: 2, proces: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Segmentatie had de aanval kunnen begrenzen.'),
          choice('B', 'Alleen softwarebeleid', 'Controleer beter welke software is toegestaan.', q.acceptable, 'end_scenario', { proces: 1, tech: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Goed, maar verklaart niet waarom alles tegelijk geraakt werd.'),
          choice('C', 'Meer communicatie', 'Zorg dat klanten sneller updates krijgen.', q.risky, 'end_scenario', { mens: 1, proces: 1, tech: 1 }, { operation: 1, reputation: 0, financial: 0 }, 'Communicatie beperkt reputatieschade, niet de technische verspreiding.'),
        ],
      },
    ],
  },
  {
    id: 'chipsoft',
    title: 'ChipSoft / Ziekenhuizen',
    year: 'concept',
    sector: 'Zorg / Softwareleverancier',
    role: 'Continuiteitsmanager ziekenhuis',
    cia: ['Availability'],
    category: ['proces', 'tech'],
    tbkLens: 'Kritiek proces',
    accent: '#ff4444',
    image: imageManifest.chipsoft,
    sources: ['Conceptscenario uit projectmateriaal'],
    intro: [
      'Het elektronisch patientendossier werkt traag of is tijdelijk niet beschikbaar. Artsen en verpleegkundigen moeten terugvallen op noodprocedures.',
      'Dit scenario draait om afhankelijkheid van kernsoftware: wat gebeurt er met het primaire proces als een leverancier of systeem uitvalt?',
    ],
    impactStats: [
      { value: 'zorg', label: 'primair proces' },
      { value: 'SLA', label: 'leveranciersafspraak' },
      { value: 'noodplan', label: 'business continuity' },
    ],
    nodes: [
      {
        id: 'start',
        title: 'EPD onbereikbaar',
        tbkTags: ['Business continuity', 'Zorgproces'],
        situation: 'De spoedeisende hulp kan dossiers niet betrouwbaar openen.',
        question: 'Wat moet als eerste gebeuren?',
        choices: [
          choice('A', 'Noodprocedure activeren', 'Schakel over naar vooraf geoefende downtime-procedure.', q.best, 'supplier', { proces: 2, tech: 1 }, { operation: 1, reputation: 0, financial: 0 }, 'Zorg kan gecontroleerd doorgaan.'),
          choice('B', 'Wachten op leverancier', 'Wacht op een update van de softwareleverancier.', q.risky, 'supplier', { proces: 2, tech: 1 }, { operation: 3, reputation: 1, financial: 1, legal: 1, trust: -1, recovery: -1, pressure: 2 }, 'De keuze lijkt rustig, maar de afdelingen gaan zelf improviseren. Medicatie-informatie raakt versnipperd, verpleegkundigen bouwen eigen lijstjes en de leverancier bepaalt feitelijk het tempo van het zorgproces.'),
          choice('C', 'Alle afspraken annuleren', 'Stop alle niet-acute zorg direct.', q.acceptable, 'supplier', { proces: 1 }, { operation: 3, reputation: 1, financial: 2, chain: 1, recovery: 0, pressure: 1 }, 'Veilig, maar grof. Acute risico\'s dalen, terwijl poli\'s, OK-planning en doorverwijzingen nieuwe achterstanden opbouwen die later opnieuw getrieerd moeten worden.'),
        ],
      },
      {
        id: 'supplier',
        title: 'Leverancier onder druk',
        tbkTags: ['Leveranciersmanagement', 'SLA'],
        situation: 'De leverancier geeft geen duidelijke hersteltijd. Afdelingen bellen zelf rond.',
        question: 'Hoe organiseer je informatie?',
        choices: [
          choice('A', 'Centraal crisiskanaal', 'Een crisisteam communiceert vaste updates naar alle afdelingen.', q.best, 'data', { proces: 2 }, { operation: 0, reputation: 0, financial: 0, trust: 1, pressure: -1 }, 'Er komt een enkele bron van waarheid. Niet elke afdeling krijgt meteen het antwoord dat zij wil, maar beslissingen worden gebaseerd op dezelfde status.'),
          choice('B', 'Afdelingen zelf laten bellen', 'Laat ieder team direct schakelen met de leverancier.', q.risky, 'data', { mens: 1, proces: 2 }, { operation: 2, reputation: 1, financial: 1, trust: -1, recovery: -1, pressure: 2 }, 'De leverancier wordt overspoeld en afdelingen krijgen verschillende antwoorden. Het lijkt snel omdat iedereen handelt, maar niemand weet meer welke informatie leidend is.'),
        ],
      },
      {
        id: 'data',
        title: 'Onzekerheid over data',
        tbkTags: ['Databetrouwbaarheid', 'Patientveiligheid'],
        situation: 'Niet duidelijk is of de laatst ingevoerde medicatiegegevens volledig zijn opgeslagen.',
        question: 'Welke CIA-impact staat centraal?',
        choices: [
          choice('A', 'Integrity', 'De vraag is of de data betrouwbaar en volledig klopt.', q.best, 'lesson', { tech: 1, proces: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Foutieve of ontbrekende data kan tot verkeerde zorgbeslissingen leiden.'),
          choice('B', 'Alleen Availability', 'Het systeem was niet beschikbaar, dus beschikbaarheid is het enige probleem.', q.acceptable, 'lesson', { tech: 1 }, { operation: 1, reputation: 0, financial: 0 }, 'Beschikbaarheid klopt, maar databetrouwbaarheid is hier minstens zo belangrijk.'),
          choice('C', 'Confidentiality', 'Het probleem is vooral dat data mogelijk openbaar is.', q.risky, 'lesson', { tech: 1, proces: 1 }, { operation: 1, reputation: 1, financial: 0 }, 'Er is nog geen aanwijzing dat data gelekt is.'),
        ],
      },
      {
        id: 'lesson',
        title: 'Structurele maatregel',
        tbkTags: ['Business continuity', 'Leveranciersmanagement'],
        situation: 'De raad van bestuur wil een structurele verbetering.',
        question: 'Wat helpt het primaire zorgproces het meest?',
        choices: [
          choice('A', 'Geteste downtime-procedure', 'Oefen periodiek hoe zorg doorgaat zonder kernsysteem.', q.best, 'end_scenario', { proces: 2, tech: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Herstelvermogen wordt concreet en toetsbaar.'),
          choice('B', 'Strengere SLA alleen', 'Leg een hogere uptime-eis vast in het contract.', q.acceptable, 'end_scenario', { proces: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Nuttig, maar lost niet op wat teams doen tijdens uitval.'),
          choice('C', 'Nieuwe software kopen', 'Vervang het systeem direct.', q.risky, 'end_scenario', { tech: 2, proces: 1 }, { operation: 2, reputation: 1, financial: 3 }, 'Duur en traag; zonder noodproces blijft het risico bestaan.'),
        ],
      },
    ],
  },
  {
    id: 'banks',
    title: 'Banken DDoS',
    year: '2018',
    sector: 'Financiele dienstverlening',
    role: 'Operationeel risicomanager bank',
    cia: ['Availability'],
    category: ['tech', 'proces'],
    tbkLens: 'Dienstverlening onder piekdruk',
    accent: '#fcd34d',
    image: imageManifest.banks,
    sources: ['NOS', 'Computable', 'CPB'],
    intro: [
      'Online bankieren en betaaldiensten worden geraakt door een DDoS-golf. Klanten kunnen niet zien of hun geld veilig is.',
      'Dit scenario draait om beschikbaarheid, klantvertrouwen en afhankelijkheid van beschermingsleveranciers.',
    ],
    impactStats: [
      { value: 'DDoS', label: 'beschikbaarheid' },
      { value: 'piek', label: 'klantcontact' },
      { value: 'keten', label: 'zelfde leverancier' },
    ],
    nodes: [
      {
        id: 'start',
        title: 'Eerste aanvalsgolf',
        tbkTags: ['Klantcommunicatie', 'Beschikbaarheid'],
        situation: 'Mobiel bankieren hapert. Klantenservice krijgt veel vragen.',
        question: 'Wat communiceer je eerst?',
        choices: [
          choice('A', 'Geld en data veilig', 'Leg uit dat beschikbaarheid geraakt is, niet saldo of klantdata.', q.best, 'capacity', { mens: 0, proces: 1, tech: 0 }, { reputation: 0, operation: 0, financial: 0 }, 'Paniek neemt af en klantenservice wordt ontlast.'),
          choice('B', 'Technisch detail', 'Publiceer vooral technische informatie over de aanval.', q.acceptable, 'capacity', { tech: 1 }, { reputation: 1, operation: 1, financial: 0, pressure: 1 }, 'Transparant, maar veel klanten begrijpen niet wat het betekent. Klantenservice krijgt extra vragen omdat de boodschap technisch klopt maar het concrete klantprobleem niet oplost.'),
          choice('C', 'Geen commentaar', 'Wacht tot alle feiten bekend zijn.', q.risky, 'capacity', { mens: 1, proces: 2 }, { reputation: 2, operation: 1, financial: 0, trust: -1, pressure: 2 }, 'Geruchten vullen het communicatiegat. De bank lijkt afwezig op het moment dat klanten juist bevestiging zoeken dat saldo en data veilig zijn.'),
        ],
      },
      {
        id: 'capacity',
        title: 'Beschermingscapaciteit',
        tbkTags: ['Leveranciersmanagement', 'Operationele weerbaarheid'],
        situation: 'De DDoS-leverancier zit tegen capaciteitsgrenzen aan.',
        question: 'Wat doe je bij toenemende aanvalsgrootte?',
        choices: [
          choice('A', 'Extra capaciteit inkopen', 'Koop tijdelijk extra bescherming in.', q.acceptable, 'dependency', { tech: 1, proces: 1 }, { financial: 2, operation: 0, reputation: 0, chain: 1, recovery: 0, pressure: 1 }, 'De directe uitval daalt, maar je koopt vooral tijd binnen dezelfde afhankelijkheid. Contracten, routing en monitoring moeten onder druk worden aangepast en de volgende piek kan opnieuw om meer capaciteit vragen.'),
          choice('B', 'Tweede leverancier activeren', 'Schakel een noodroute via een tweede leverancier in.', q.best, 'dependency', { proces: 2, tech: 1 }, { financial: 1, operation: 0, reputation: 0 }, 'Complexer, maar vermindert afhankelijkheid van een punt.'),
          choice('C', 'Afwachten', 'Accepteer het risico omdat extra capaciteit duur is.', q.risky, 'dependency', { proces: 2, tech: 1 }, { financial: 1, operation: 3, reputation: 2, chain: 1, trust: -1, pressure: 2 }, 'De kosten blijven vandaag lager, maar een nieuwe piek leidt tot extra uitval. Klantenservice krijgt de rekening in vragen, klachten en onzekerheid over betaaldiensten.'),
        ],
      },
      {
        id: 'dependency',
        title: 'Ketenafhankelijkheid',
        tbkTags: ['Systeemrisico', 'Leveranciersmanagement'],
        situation: 'Een rapport laat zien dat meerdere banken dezelfde DDoS-leverancier gebruiken.',
        question: 'Welke structurele maatregel adviseer je?',
        choices: [
          choice('A', 'Diversificatie', 'Werk met meerdere beschermingslagen en leveranciers.', q.best, 'end_scenario', { proces: 2, tech: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Minder afhankelijk van een enkele partij.'),
          choice('B', 'Alleen klantvoorlichting', 'Leg klanten beter uit wat een DDoS is.', q.acceptable, 'end_scenario', { mens: 1, proces: 0 }, { operation: 1, reputation: 0, financial: 0, trust: 1 }, 'Helpt vertrouwen en verlaagt paniek, maar de technische afhankelijkheid blijft bestaan. Bij de volgende aanval kun je beter uitleggen waarom klanten vastlopen, niet voorkomen dat ze vastlopen.'),
          choice('C', 'Alleen intern monitoren', 'Investeer vooral in extra dashboards.', q.risky, 'end_scenario', { tech: 1, proces: 1 }, { operation: 2, reputation: 1, financial: 1, recovery: -1, pressure: 1 }, 'Je ziet problemen sneller, maar kunt ze niet altijd opvangen. Monitoring zonder alternatieve route verandert incidenten in beter gedocumenteerde uitval.'),
        ],
      },
    ],
  },
  {
    id: 'odido',
    title: 'Odido Datalek',
    year: '2023',
    sector: 'Telecom / Leveranciersrisico',
    role: 'IT-operations manager',
    cia: ['Confidentiality'],
    category: ['proces'],
    tbkLens: 'Leverancierstoegang',
    accent: '#c084fc',
    image: imageManifest.odido,
    sources: ['NOS', 'RTL Nieuws', 'Odido'],
    intro: [
      'Een leveranciersaccount exporteert veel meer records dan normaal. De migratieplanning maakt het signaal plausibel, maar het volume is verdacht.',
      'Dit scenario draait om least privilege, logging en AVG-meldplicht: je beveiliging stopt niet bij de grens van je eigen organisatie.',
    ],
    impactStats: [
      { value: '6.3M', label: 'records mogelijk geraakt' },
      { value: '72u', label: 'AVG-meldtermijn' },
      { value: 'extern', label: 'leveranciersaccount' },
    ],
    nodes: [
      {
        id: 'start',
        title: 'Bulk export',
        tbkTags: ['Leveranciersmanagement', 'Toegangsbeheer'],
        situation: 'Een extern serviceaccount exporteert in korte tijd honderdduizenden records.',
        question: 'Wat doe je met het account?',
        choices: [
          choice('A', 'Direct blokkeren', 'Blokkeer het account en bel de leverancier via bekend nummer.', q.best, 'supplier', { proces: 2, tech: 1 }, { operation: 1, reputation: 0, financial: 0 }, 'De export stopt vroeg en verificatie loopt via betrouwbaar kanaal.'),
          choice('B', 'Limiet zetten', 'Sta export toe tot een hogere limiet en monitor.', q.acceptable, 'supplier', { proces: 1, tech: 1 }, { operation: 0, reputation: 1, financial: 1, legal: 1, recovery: -1, pressure: 1 }, 'De migratie wordt minder verstoord, maar je accepteert extra databeweging terwijl de oorzaak onzeker is. Als het misbruik blijkt, is de schade groter en moet je uitleggen waarom de kraan niet dichtging.'),
          choice('C', 'Mail sturen', 'Vraag per mail of de export klopt.', q.risky, 'supplier', { mens: 1, proces: 2 }, { operation: 0, reputation: 2, financial: 1 }, 'Als het account overgenomen is, praat je mogelijk met de aanvaller.'),
        ],
      },
      {
        id: 'supplier',
        title: 'Boze leverancier',
        tbkTags: ['Governance', 'Leveranciersafspraken'],
        situation: 'De leverancier klaagt dat de migratie vertraging oploopt en vraagt om deblokkade.',
        question: 'Welke controle hoort hier?',
        choices: [
          choice('A', 'Documentatie eisen', 'Vraag schriftelijke projectautorisatie en laat CISO meekijken.', q.best, 'avg', { proces: 2 }, { operation: 0, reputation: 0, financial: 0 }, 'Zakelijke druk wordt gescheiden van securitybesluitvorming.'),
          choice('B', 'Deblokkeren', 'Herstel toegang omdat de uitleg plausibel klinkt.', q.risky, 'avg', { mens: 1, proces: 2 }, { reputation: 2, financial: 1, operation: 0 }, 'Vertrouwen vervangt bewijs.'),
          choice('C', 'Alles naar legal', 'Wacht tot juridisch advies klaar is.', q.acceptable, 'avg', { proces: 1 }, { operation: 1, reputation: 1, financial: 0, legal: 0, recovery: -1, pressure: 1 }, 'Zorgvuldig, maar security-actie mag niet stilvallen. Terwijl legal formuleert, blijft operationeel onduidelijk wie toegang mag herstellen, welke data geraakt is en wanneer de meldklok start.'),
        ],
      },
      {
        id: 'avg',
        title: 'De AVG-klok',
        tbkTags: ['Compliance', 'Klantcommunicatie'],
        situation: 'Er is waarschijnlijk sprake van een datalek met persoonsgegevens.',
        question: 'Hoe ga je om met melden?',
        choices: [
          choice('A', 'Melden met onzekerheid', 'Meld bij de AP met wat bekend is en vul later aan.', q.best, 'lesson', { proces: 2 }, { reputation: 0, financial: 0, operation: 0 }, 'De wettelijke klok wordt serieus genomen.'),
          choice('B', 'Wachten op perfect rapport', 'Meld pas als alle forensische details rond zijn.', q.risky, 'lesson', { proces: 2 }, { reputation: 2, financial: 2, operation: 0 }, 'Volledigheid kan te laat komen.'),
          choice('C', 'Klanten eerst, AP later', 'Informeer klanten direct en meld daarna formeel.', q.acceptable, 'lesson', { proces: 1, mens: 1 }, { reputation: 1, financial: 0, operation: 0, legal: 1, pressure: 1 }, 'Transparant, maar volgorde en feiten moeten strak worden bewaakt. Als klanten eerder andere details horen dan de toezichthouder, ontstaat extra uitlegwerk en compliance-druk.'),
        ],
      },
      {
        id: 'lesson',
        title: 'Structurele maatregel',
        tbkTags: ['Least privilege', 'Logging'],
        situation: 'De oorzaak blijkt te ruime leverancierstoegang.',
        question: 'Wat voorkomt herhaling het best?',
        choices: [
          choice('A', 'Least privilege en alerts', 'Beperk externe toegang strikt en monitor bulkacties automatisch.', q.best, 'end_scenario', { proces: 2, tech: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Bron, detectie en controle worden gecombineerd.'),
          choice('B', 'Alleen contractboetes', 'Maak leveranciers financieel aansprakelijk.', q.acceptable, 'end_scenario', { proces: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Regelt gevolgen, maar voorkomt export niet.'),
          choice('C', 'Alleen PR-plan', 'Maak betere klantcommunicatie voor datalekken.', q.risky, 'end_scenario', { proces: 1, mens: 1 }, { reputation: 1, financial: 0, operation: 0 }, 'Nuttig na afloop, te laat als primaire maatregel.'),
        ],
      },
    ],
  },
  {
    id: 'pathe',
    title: 'Pathe CEO-fraude',
    year: '2018',
    sector: 'Entertainment / Finance process',
    role: 'CFO Nederland',
    cia: ['Integrity'],
    category: ['mens', 'proces'],
    tbkLens: 'Interne controle',
    accent: '#9333ea',
    image: imageManifest.pathe,
    sources: ['NOS', 'Accountant.nl', 'Vonnis Amsterdam'],
    intro: [
      'Een overtuigende mail van het hoofdkantoor vraagt om een geheime spoedbetaling. Het domein lijkt te kloppen, maar wijkt subtiel af.',
      'Dit scenario draait om integrity: informatie lijkt betrouwbaar, maar is vervalst. Besluitvorming en betalingsprocessen worden aangevallen.',
    ],
    impactStats: [
      { value: '19.2M', label: 'euro schade' },
      { value: 'BEC', label: 'business email compromise' },
      { value: '4-ogen', label: 'interne controle' },
    ],
    nodes: [
      {
        id: 'start',
        title: 'De eerste betaling',
        tbkTags: ['Interne controle', 'Social engineering'],
        situation: 'De mail vraagt geheimhouding en verwijst naar een overname. Het afzenderdomein wijkt een woord af.',
        question: 'Wat doe je voor betaling?',
        choices: [
          choice('A', 'Tweede kanaal', 'Bel het hoofdkantoor via een bekend officieel nummer.', q.best, 'discover', { mens: 1, proces: 2 }, { operation: 0, reputation: 0, financial: 0 }, 'Fraude wordt ontdekt voordat geld vertrekt.'),
          choice('B', 'Betalen', 'Betaal omdat de vraag urgent en vertrouwelijk is.', q.risky, 'second', { mens: 2, proces: 2 }, { financial: 3, reputation: 1, operation: 0 }, 'De eerste betaling verdwijnt en de fraudeur komt terug.'),
          choice('C', 'Mail terug', 'Vraag extra informatie via dezelfde mailthread.', q.acceptable, 'second', { mens: 1, proces: 1 }, { financial: 1, reputation: 0, operation: 0, trust: -1, pressure: 1 }, 'Je zoekt bewijs, maar bij de verkeerde partij. De fraudeur krijgt tijd om geloofwaardiger te reageren en jouw twijfel wordt onderdeel van zijn script.'),
        ],
      },
      {
        id: 'discover',
        title: 'Fraude ontdekt',
        tbkTags: ['Incidentmelding', 'Governance'],
        situation: 'Het hoofdkantoor weet nergens van. Er is nog geen financiele schade.',
        question: 'Wat is de juiste vervolgstap?',
        choices: [
          choice('A', 'Melden en vastleggen', 'Informeer bestuur, bank en politie; bewaar bewijs.', q.best, 'lesson', { proces: 1 }, { financial: 0, reputation: 0, operation: 0 }, 'Snel melden helpt detectie en voorkomt vervolgschade.'),
          choice('B', 'Stil intern uitzoeken', 'Onderzoek eerst zelf wat er gebeurd is.', q.acceptable, 'lesson', { proces: 1 }, { operation: 1, reputation: 1, financial: 0, recovery: -1, pressure: 1 }, 'Begrijpelijk, maar waarschuwingen komen later. Bank en bestuur missen vroege signalen, waardoor vervolgschade minder snel geblokkeerd kan worden.'),
        ],
      },
      {
        id: 'second',
        title: 'De tweede mail',
        tbkTags: ['Tijdsdruk', 'Betalingsmandaat'],
        situation: 'Na de eerste betaling komt een groter verzoek. De psychologische druk neemt toe.',
        question: 'Wat doorbreekt de fraude?',
        choices: [
          choice('A', 'Stop en bel', 'Weiger betaling tot verificatie via officieel kanaal is gelukt.', q.best, 'lesson', { mens: 1, proces: 2 }, { financial: 0, reputation: 0, operation: 0 }, 'De schade stopt en het patroon wordt zichtbaar.'),
          choice('B', 'Doorgaan', 'Betaal omdat stoppen vreemd voelt na de eerste betaling.', q.risky, 'lesson', { mens: 2, proces: 2 }, { financial: 3, reputation: 2, operation: 0 }, 'Sunk cost-denken vergroot de schade.'),
          choice('C', 'Videobel vragen', 'Vraag de CEO om mondelinge bevestiging.', q.acceptable, 'lesson', { mens: 1, proces: 1 }, { financial: 1, reputation: 0, operation: 0, pressure: 1 }, 'Een goed signaal, maar alleen veilig als je het kanaal zelf initieert. Als je het gesprek via de bestaande mailthread laat regelen, kan de aanvaller de verificatie alsnog sturen.'),
        ],
      },
      {
        id: 'lesson',
        title: 'Structurele controle',
        tbkTags: ['Interne controle', 'Governance'],
        situation: 'De les is niet dat iemand dom was, maar dat het proces druk niet opving.',
        question: 'Welke maatregel hoort bovenaan?',
        choices: [
          choice('A', 'Vierogen plus verificatie', 'Betalingen boven grensbedrag vereisen twee personen en tweede kanaal.', q.best, 'end_scenario', { proces: 2, mens: 1 }, { financial: 0, reputation: 0, operation: 0 }, 'Een vervalste mail is nooit genoeg.'),
          choice('B', 'Alleen bewustwording', 'Train finance-medewerkers op CEO-fraude.', q.acceptable, 'end_scenario', { mens: 1, proces: 1 }, { financial: 0, reputation: 0, operation: 0 }, 'Nodig, maar zonder procescontrole blijft een fout mogelijk rampzalig.'),
          choice('C', 'Alleen e-mailfilter', 'Gebruik DMARC/SPF en filtering.', q.acceptable, 'end_scenario', { tech: 1, proces: 0 }, { financial: 0, reputation: 0, operation: 0 }, 'Sterk technisch vangnet, maar niet genoeg als enige controle.'),
        ],
      },
    ],
  },
]
