import { imageManifest } from '../assets/imageManifest.js'

const q = {
  best: 'best',
  acceptable: 'acceptable',
  risky: 'risky',
}

function choice(id, label, text, quality, next, risk, meters, consequence) {
  return { id, label, text, quality, next, risk, meters, consequence }
}

export const scenarios = [
  {
    id: 'vdl',
    title: 'VDL Groep',
    year: '2021',
    sector: 'Maakindustrie / Automotive',
    role: 'Operationeel directeur VDL Nedcar',
    cia: ['Availability'],
    category: ['proces', 'tech'],
    tbkLens: 'Productiecontinuiteit',
    accent: '#ff8c00',
    image: imageManifest.vdl,
    sources: ['NOS', 'Omroep Brabant', 'Maakindustrie Nieuws'],
    intro: [
      'Donderdag 03:47. De nachtdienst belt: systemen vallen een voor een uit. Om 06:00 staan medewerkers bij de poort en BMW verwacht onderdelen.',
      'Dit scenario draait om productiecontinuiteit: als digitale planning, voorraad en kwaliteitsregistratie uitvallen, staat niet alleen IT stil maar ook de keten.',
    ],
    impactStats: [
      { value: '15k', label: 'medewerkers wereldwijd' },
      { value: '1 maand', label: 'volledig herstel' },
      { value: 'keten', label: 'klanten en leveranciers geraakt' },
    ],
    nodes: [
      {
        id: 'start',
        title: 'De eerste ochtend',
        tbkTags: ['Productiecontinuiteit', 'Kwaliteitsborging'],
        situation: 'Je weet nog niet of het een storing of aanval is. Enkele systemen lijken nog te werken.',
        question: 'Wat is je eerste managementbeslissing?',
        choices: [
          choice('A', 'Volledig isoleren', 'Leg alle digitale systemen stil en stuur teams naar crisisprocedure.', q.best, 'ransom', { proces: 2, tech: 1 }, { operation: 1, reputation: 0, financial: 1 }, 'Verdere verspreiding wordt beperkt, maar productie stopt direct.'),
          choice('B', 'Handmatig doorwerken', 'Laat teams zonder digitale afhankelijkheid op papier verder werken.', q.acceptable, 'quality', { proces: 1, tech: 0 }, { operation: 1, reputation: 0, financial: 0 }, 'Er is beperkte output, maar traceerbaarheid wordt een probleem.'),
          choice('C', 'Lijn testen', 'Start een productielijn met planning opnieuw op om te zien wat nog werkt.', q.risky, 'ransom', { proces: 2, tech: 2 }, { operation: 3, reputation: 1, financial: 2 }, 'De aanval verspreidt zich naar systemen die nog schoon leken.'),
        ],
      },
      {
        id: 'quality',
        title: 'Handmatig zonder traceerbaarheid',
        tbkTags: ['Kwaliteitsborging', 'Klantafspraken'],
        situation: 'BMW accepteert veiligheidsonderdelen alleen met controleerbare kwaliteitsdata.',
        question: 'Hoe houd je operatie en kwaliteit in balans?',
        choices: [
          choice('A', 'Tijdelijke uitzondering vragen', 'Vraag BMW formeel om tijdelijke handmatige documentatie te accepteren.', q.best, 'ransom', { proces: 1, mens: 0 }, { operation: 0, reputation: 0, financial: 0 }, 'De klant krijgt transparantie en kan een gecontroleerde uitzondering beoordelen.'),
          choice('B', 'Doorgaan en later herstellen', 'Maak voorraad en vul digitale registratie later aan.', q.acceptable, 'ransom', { proces: 1, tech: 0 }, { operation: 1, reputation: 1, financial: 1 }, 'Output lijkt gered, maar vrijgave en claims worden later ingewikkeld.'),
          choice('C', 'Alles alsnog stoppen', 'Stop handmatige productie volledig tot IT hersteld is.', q.acceptable, 'ransom', { proces: 0, tech: 0 }, { operation: 1, reputation: 0, financial: 1 }, 'Veilig maar kostbaar; de klantdruk neemt toe.'),
        ],
      },
      {
        id: 'ransom',
        title: 'De losgeldvraag',
        tbkTags: ['Herstelvermogen', 'Governance'],
        situation: 'Ransomware eist betaling. Back-ups bestaan, maar zijn niet allemaal actueel.',
        question: 'Welke keuze past het best bij herstelvermogen?',
        choices: [
          choice('A', 'Herstellen via back-ups', 'Niet betalen; herstel via back-ups en accepteer dat recente data opnieuw moet.', q.best, 'lesson', { proces: 1, tech: 1 }, { operation: 1, reputation: 0, financial: 1 }, 'Herstel duurt langer, maar het bedrijf beloont criminelen niet.'),
          choice('B', 'Betalen', 'Betaal omdat stilstand per dag duurder lijkt dan losgeld.', q.risky, 'lesson', { mens: 1, proces: 2, tech: 1 }, { operation: 2, reputation: 2, financial: 2 }, 'De sleutel werkt onzeker en het bedrijf vergroot afhankelijkheid van criminelen.'),
          choice('C', 'Onderhandelen', 'Probeer tijd te winnen terwijl IT alternatieven onderzoekt.', q.acceptable, 'lesson', { proces: 1, tech: 0 }, { operation: 1, reputation: 1, financial: 1 }, 'Je wint mogelijk tijd, maar herstel blijft afhankelijk van back-ups.'),
        ],
      },
      {
        id: 'lesson',
        title: 'Structurele les',
        tbkTags: ['Toegangsbeheer', 'Netwerksegmentatie'],
        situation: 'De board wil weten welke maatregel de grootste structurele winst geeft.',
        question: 'Welke maatregel prioriteer je?',
        choices: [
          choice('A', 'MFA op externe toegang', 'Maak gestolen inloggegevens waardeloos zonder tweede factor.', q.best, 'end_scenario', { mens: 0, proces: 1, tech: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'De waarschijnlijke ingang wordt direct aangepakt.'),
          choice('B', 'Netwerksegmentatie', 'Scheid kantoor-IT en productie-IT hard van elkaar.', q.acceptable, 'end_scenario', { proces: 1, tech: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Sterk voor schadebeperking, vooral als een aanval al binnen is.'),
          choice('C', 'Alleen extra training', 'Train medewerkers en communiceer scherper over phishing.', q.risky, 'end_scenario', { mens: 1, proces: 1, tech: 1 }, { operation: 1, reputation: 0, financial: 0 }, 'Nuttig, maar te smal als enige maatregel voor productie-IT.'),
        ],
      },
    ],
  },
  {
    id: 'maersk',
    title: 'Maersk / NotPetya',
    year: '2017',
    sector: 'Logistiek / Supply chain',
    role: 'Head of Operations APM Terminals Rotterdam',
    cia: ['Availability'],
    category: ['tech', 'proces'],
    tbkLens: 'Ketenafhankelijkheid',
    accent: '#00d4ff',
    image: imageManifest.maersk,
    sources: ['Wired', 'The Register', 'NOS'],
    intro: [
      'De Rotterdamse terminal valt stil. Zonder containervolgingssysteem weet niemand welke container waar staat of wat ermee mag gebeuren.',
      'Dit scenario draait om ketenafhankelijkheid: een software-update elders in de wereld kan fysieke goederenstromen in Rotterdam stilleggen.',
    ],
    impactStats: [
      { value: '76', label: 'terminals geraakt' },
      { value: '$300M', label: 'geschatte schade' },
      { value: '45k', label: 'computers hersteld' },
    ],
    nodes: [
      {
        id: 'start',
        title: 'Terminal open of dicht',
        tbkTags: ['Logistiek', 'Veiligheid', 'Ketenafhankelijkheid'],
        situation: 'Vijf schepen wachten. Zonder systeem is gevaarlijke lading niet betrouwbaar te lokaliseren.',
        question: 'Wat doe je met de terminal?',
        choices: [
          choice('A', 'Sluit de terminal', 'Stop de operatie tot duidelijk is wat veilig kan.', q.best, 'priority', { proces: 2, tech: 1 }, { operation: 2, reputation: 0, financial: 1 }, 'Schepen worden omgeleid, maar veiligheidsrisico blijft beheersbaar.'),
          choice('B', 'Alles handmatig', 'Laat teams met manifesten en Excel doorwerken.', q.risky, 'priority', { proces: 2, tech: 1 }, { operation: 2, reputation: 2, financial: 1 }, 'Er ontstaan verschillende versies van de waarheid.'),
          choice('C', 'Alleen veilige lading', 'Accepteer tijdelijk alleen niet-gevaarlijke lading.', q.acceptable, 'priority', { proces: 1, tech: 1 }, { operation: 1, reputation: 0, financial: 1 }, 'Een compromis: minder capaciteit, maar minder veiligheidsrisico.'),
        ],
      },
      {
        id: 'priority',
        title: 'Beperkte capaciteit',
        tbkTags: ['Prioriteren', 'Business continuity'],
        situation: 'Handmatig kan maar een deel van de operatie draaien.',
        question: 'Welke lading krijgt prioriteit?',
        choices: [
          choice('A', 'Kritieke lading eerst', 'Medische, bederfelijke en veiligheidskritieke lading krijgen voorrang.', q.best, 'recovery', { proces: 1, mens: 0 }, { operation: 0, reputation: 0, financial: 0 }, 'Capaciteit wordt gekoppeld aan maatschappelijke en operationele impact.'),
          choice('B', 'Hardste klant eerst', 'Geef voorrang aan klanten die escaleren.', q.risky, 'recovery', { mens: 1, proces: 2 }, { operation: 1, reputation: 2, financial: 1 }, 'Je beloont druk in plaats van impact.'),
          choice('C', 'First-in-first-out', 'Volg de normale volgorde ondanks het incident.', q.acceptable, 'recovery', { proces: 1, tech: 0 }, { operation: 1, reputation: 0, financial: 1 }, 'Eerlijk, maar niet altijd bedrijfskundig verstandig.'),
        ],
      },
      {
        id: 'recovery',
        title: 'Ghana-server',
        tbkTags: ['Herstelvermogen', 'Globale operatie'],
        situation: 'Een offline server in Ghana bevat de enige bruikbare kopie van cruciale netwerkdata.',
        question: 'Wat prioriteer je?',
        choices: [
          choice('A', 'Globaal herstel', 'Begin wereldwijd herstel zodra de data beschikbaar is.', q.best, 'lesson', { proces: 1, tech: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Het hele netwerk komt sneller terug.'),
          choice('B', 'Rotterdam eerst', 'Wacht op een lokale kopie zodat Rotterdam sneller herstelt.', q.acceptable, 'lesson', { proces: 1, tech: 0 }, { operation: 1, reputation: 0, financial: 1 }, 'Lokaal aantrekkelijk, maar vertraagt de keten.'),
        ],
      },
      {
        id: 'lesson',
        title: 'Structurele zwakte',
        tbkTags: ['Netwerksegmentatie', 'Supply chain'],
        situation: 'De aanval begon via software, maar de wereldwijde schade kwam door snelle verspreiding.',
        question: 'Welke zwakte maakte de schade zo groot?',
        choices: [
          choice('A', 'Geen segmentatie', 'Een besmet kantoor kon het wereldwijde netwerk raken.', q.best, 'end_scenario', { tech: 2, proces: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Segmentatie had de aanval kunnen begrenzen.'),
          choice('B', 'Alleen softwarebeleid', 'Controleer beter welke software is toegestaan.', q.acceptable, 'end_scenario', { proces: 1, tech: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Goed, maar verklaart niet waarom alles tegelijk geraakt werd.'),
          choice('C', 'Meer communicatie', 'Zorg dat klanten sneller updates krijgen.', q.risky, 'end_scenario', { mens: 1, proces: 1, tech: 1 }, { operation: 1, reputation: 0, financial: 0 }, 'Communicatie beperkt reputatieschade, niet de technische verspreiding.'),
        ],
      },
    ],
  },
  {
    id: 'chipsoft',
    title: 'ChipSoft / Ziekenhuizen',
    year: 'concept',
    sector: 'Zorg / Softwareleverancier',
    role: 'Continuiteitsmanager ziekenhuis',
    cia: ['Availability'],
    category: ['proces', 'tech'],
    tbkLens: 'Kritiek proces',
    accent: '#ff4444',
    image: imageManifest.chipsoft,
    sources: ['Conceptscenario uit projectmateriaal'],
    intro: [
      'Het elektronisch patientendossier werkt traag of is tijdelijk niet beschikbaar. Artsen en verpleegkundigen moeten terugvallen op noodprocedures.',
      'Dit scenario draait om afhankelijkheid van kernsoftware: wat gebeurt er met het primaire proces als een leverancier of systeem uitvalt?',
    ],
    impactStats: [
      { value: 'zorg', label: 'primair proces' },
      { value: 'SLA', label: 'leveranciersafspraak' },
      { value: 'noodplan', label: 'business continuity' },
    ],
    nodes: [
      {
        id: 'start',
        title: 'EPD onbereikbaar',
        tbkTags: ['Business continuity', 'Zorgproces'],
        situation: 'De spoedeisende hulp kan dossiers niet betrouwbaar openen.',
        question: 'Wat moet als eerste gebeuren?',
        choices: [
          choice('A', 'Noodprocedure activeren', 'Schakel over naar vooraf geoefende downtime-procedure.', q.best, 'supplier', { proces: 2, tech: 1 }, { operation: 1, reputation: 0, financial: 0 }, 'Zorg kan gecontroleerd doorgaan.'),
          choice('B', 'Wachten op leverancier', 'Wacht op een update van de softwareleverancier.', q.risky, 'supplier', { proces: 2, tech: 1 }, { operation: 3, reputation: 1, financial: 1 }, 'Teams improviseren en informatie raakt versnipperd.'),
          choice('C', 'Alle afspraken annuleren', 'Stop alle niet-acute zorg direct.', q.acceptable, 'supplier', { proces: 1 }, { operation: 2, reputation: 1, financial: 1 }, 'Veilig, maar mogelijk te grof zonder triage.'),
        ],
      },
      {
        id: 'supplier',
        title: 'Leverancier onder druk',
        tbkTags: ['Leveranciersmanagement', 'SLA'],
        situation: 'De leverancier geeft geen duidelijke hersteltijd. Afdelingen bellen zelf rond.',
        question: 'Hoe organiseer je informatie?',
        choices: [
          choice('A', 'Centraal crisiskanaal', 'Een crisisteam communiceert vaste updates naar alle afdelingen.', q.best, 'data', { proces: 2 }, { operation: 0, reputation: 0, financial: 0 }, 'Er komt een enkele bron van waarheid.'),
          choice('B', 'Afdelingen zelf laten bellen', 'Laat ieder team direct schakelen met de leverancier.', q.risky, 'data', { mens: 1, proces: 2 }, { operation: 2, reputation: 1, financial: 0 }, 'De leverancier wordt overspoeld en afdelingen krijgen verschillende antwoorden.'),
        ],
      },
      {
        id: 'data',
        title: 'Onzekerheid over data',
        tbkTags: ['Databetrouwbaarheid', 'Patientveiligheid'],
        situation: 'Niet duidelijk is of de laatst ingevoerde medicatiegegevens volledig zijn opgeslagen.',
        question: 'Welke CIA-impact staat centraal?',
        choices: [
          choice('A', 'Integrity', 'De vraag is of de data betrouwbaar en volledig klopt.', q.best, 'lesson', { tech: 1, proces: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Foutieve of ontbrekende data kan tot verkeerde zorgbeslissingen leiden.'),
          choice('B', 'Alleen Availability', 'Het systeem was niet beschikbaar, dus beschikbaarheid is het enige probleem.', q.acceptable, 'lesson', { tech: 1 }, { operation: 1, reputation: 0, financial: 0 }, 'Beschikbaarheid klopt, maar databetrouwbaarheid is hier minstens zo belangrijk.'),
          choice('C', 'Confidentiality', 'Het probleem is vooral dat data mogelijk openbaar is.', q.risky, 'lesson', { tech: 1, proces: 1 }, { operation: 1, reputation: 1, financial: 0 }, 'Er is nog geen aanwijzing dat data gelekt is.'),
        ],
      },
      {
        id: 'lesson',
        title: 'Structurele maatregel',
        tbkTags: ['Business continuity', 'Leveranciersmanagement'],
        situation: 'De raad van bestuur wil een structurele verbetering.',
        question: 'Wat helpt het primaire zorgproces het meest?',
        choices: [
          choice('A', 'Geteste downtime-procedure', 'Oefen periodiek hoe zorg doorgaat zonder kernsysteem.', q.best, 'end_scenario', { proces: 2, tech: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Herstelvermogen wordt concreet en toetsbaar.'),
          choice('B', 'Strengere SLA alleen', 'Leg een hogere uptime-eis vast in het contract.', q.acceptable, 'end_scenario', { proces: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Nuttig, maar lost niet op wat teams doen tijdens uitval.'),
          choice('C', 'Nieuwe software kopen', 'Vervang het systeem direct.', q.risky, 'end_scenario', { tech: 2, proces: 1 }, { operation: 2, reputation: 1, financial: 3 }, 'Duur en traag; zonder noodproces blijft het risico bestaan.'),
        ],
      },
    ],
  },
  {
    id: 'banks',
    title: 'Banken DDoS',
    year: '2018',
    sector: 'Financiele dienstverlening',
    role: 'Operationeel risicomanager bank',
    cia: ['Availability'],
    category: ['tech', 'proces'],
    tbkLens: 'Dienstverlening onder piekdruk',
    accent: '#fcd34d',
    image: imageManifest.banks,
    sources: ['NOS', 'Computable', 'CPB'],
    intro: [
      'Online bankieren en betaaldiensten worden geraakt door een DDoS-golf. Klanten kunnen niet zien of hun geld veilig is.',
      'Dit scenario draait om beschikbaarheid, klantvertrouwen en afhankelijkheid van beschermingsleveranciers.',
    ],
    impactStats: [
      { value: 'DDoS', label: 'beschikbaarheid' },
      { value: 'piek', label: 'klantcontact' },
      { value: 'keten', label: 'zelfde leverancier' },
    ],
    nodes: [
      {
        id: 'start',
        title: 'Eerste aanvalsgolf',
        tbkTags: ['Klantcommunicatie', 'Beschikbaarheid'],
        situation: 'Mobiel bankieren hapert. Klantenservice krijgt veel vragen.',
        question: 'Wat communiceer je eerst?',
        choices: [
          choice('A', 'Geld en data veilig', 'Leg uit dat beschikbaarheid geraakt is, niet saldo of klantdata.', q.best, 'capacity', { mens: 0, proces: 1, tech: 0 }, { reputation: 0, operation: 0, financial: 0 }, 'Paniek neemt af en klantenservice wordt ontlast.'),
          choice('B', 'Technisch detail', 'Publiceer vooral technische informatie over de aanval.', q.acceptable, 'capacity', { tech: 1 }, { reputation: 1, operation: 0, financial: 0 }, 'Transparant, maar veel klanten begrijpen niet wat het betekent.'),
          choice('C', 'Geen commentaar', 'Wacht tot alle feiten bekend zijn.', q.risky, 'capacity', { mens: 1, proces: 2 }, { reputation: 2, operation: 1, financial: 0 }, 'Geruchten vullen het communicatiegat.'),
        ],
      },
      {
        id: 'capacity',
        title: 'Beschermingscapaciteit',
        tbkTags: ['Leveranciersmanagement', 'Operationele weerbaarheid'],
        situation: 'De DDoS-leverancier zit tegen capaciteitsgrenzen aan.',
        question: 'Wat doe je bij toenemende aanvalsgrootte?',
        choices: [
          choice('A', 'Extra capaciteit inkopen', 'Koop tijdelijk extra bescherming in.', q.acceptable, 'dependency', { tech: 1, proces: 1 }, { financial: 1, operation: 0, reputation: 0 }, 'Duur, maar verlaagt directe uitval.'),
          choice('B', 'Tweede leverancier activeren', 'Schakel een noodroute via een tweede leverancier in.', q.best, 'dependency', { proces: 2, tech: 1 }, { financial: 1, operation: 0, reputation: 0 }, 'Complexer, maar vermindert afhankelijkheid van een punt.'),
          choice('C', 'Afwachten', 'Accepteer het risico omdat extra capaciteit duur is.', q.risky, 'dependency', { proces: 2, tech: 1 }, { financial: 1, operation: 2, reputation: 2 }, 'Een nieuwe piek leidt tot extra uitval.'),
        ],
      },
      {
        id: 'dependency',
        title: 'Ketenafhankelijkheid',
        tbkTags: ['Systeemrisico', 'Leveranciersmanagement'],
        situation: 'Een rapport laat zien dat meerdere banken dezelfde DDoS-leverancier gebruiken.',
        question: 'Welke structurele maatregel adviseer je?',
        choices: [
          choice('A', 'Diversificatie', 'Werk met meerdere beschermingslagen en leveranciers.', q.best, 'end_scenario', { proces: 2, tech: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Minder afhankelijk van een enkele partij.'),
          choice('B', 'Alleen klantvoorlichting', 'Leg klanten beter uit wat een DDoS is.', q.acceptable, 'end_scenario', { mens: 1, proces: 0 }, { operation: 0, reputation: 0, financial: 0 }, 'Helpt vertrouwen, maar lost technische afhankelijkheid niet op.'),
          choice('C', 'Alleen intern monitoren', 'Investeer vooral in extra dashboards.', q.risky, 'end_scenario', { tech: 1, proces: 1 }, { operation: 1, reputation: 0, financial: 1 }, 'Je ziet problemen sneller, maar kan ze niet altijd opvangen.'),
        ],
      },
    ],
  },
  {
    id: 'odido',
    title: 'Odido Datalek',
    year: '2023',
    sector: 'Telecom / Leveranciersrisico',
    role: 'IT-operations manager',
    cia: ['Confidentiality'],
    category: ['proces'],
    tbkLens: 'Leverancierstoegang',
    accent: '#c084fc',
    image: imageManifest.odido,
    sources: ['NOS', 'RTL Nieuws', 'Odido'],
    intro: [
      'Een leveranciersaccount exporteert veel meer records dan normaal. De migratieplanning maakt het signaal plausibel, maar het volume is verdacht.',
      'Dit scenario draait om least privilege, logging en AVG-meldplicht: je beveiliging stopt niet bij de grens van je eigen organisatie.',
    ],
    impactStats: [
      { value: '6.3M', label: 'records mogelijk geraakt' },
      { value: '72u', label: 'AVG-meldtermijn' },
      { value: 'extern', label: 'leveranciersaccount' },
    ],
    nodes: [
      {
        id: 'start',
        title: 'Bulk export',
        tbkTags: ['Leveranciersmanagement', 'Toegangsbeheer'],
        situation: 'Een extern serviceaccount exporteert in korte tijd honderdduizenden records.',
        question: 'Wat doe je met het account?',
        choices: [
          choice('A', 'Direct blokkeren', 'Blokkeer het account en bel de leverancier via bekend nummer.', q.best, 'supplier', { proces: 2, tech: 1 }, { operation: 1, reputation: 0, financial: 0 }, 'De export stopt vroeg en verificatie loopt via betrouwbaar kanaal.'),
          choice('B', 'Limiet zetten', 'Sta export toe tot een hogere limiet en monitor.', q.acceptable, 'supplier', { proces: 1, tech: 1 }, { operation: 0, reputation: 1, financial: 0 }, 'Minder verstoring, maar meer data kan buitenkomen.'),
          choice('C', 'Mail sturen', 'Vraag per mail of de export klopt.', q.risky, 'supplier', { mens: 1, proces: 2 }, { operation: 0, reputation: 2, financial: 1 }, 'Als het account overgenomen is, praat je mogelijk met de aanvaller.'),
        ],
      },
      {
        id: 'supplier',
        title: 'Boze leverancier',
        tbkTags: ['Governance', 'Leveranciersafspraken'],
        situation: 'De leverancier klaagt dat de migratie vertraging oploopt en vraagt om deblokkade.',
        question: 'Welke controle hoort hier?',
        choices: [
          choice('A', 'Documentatie eisen', 'Vraag schriftelijke projectautorisatie en laat CISO meekijken.', q.best, 'avg', { proces: 2 }, { operation: 0, reputation: 0, financial: 0 }, 'Zakelijke druk wordt gescheiden van securitybesluitvorming.'),
          choice('B', 'Deblokkeren', 'Herstel toegang omdat de uitleg plausibel klinkt.', q.risky, 'avg', { mens: 1, proces: 2 }, { reputation: 2, financial: 1, operation: 0 }, 'Vertrouwen vervangt bewijs.'),
          choice('C', 'Alles naar legal', 'Wacht tot juridisch advies klaar is.', q.acceptable, 'avg', { proces: 1 }, { operation: 1, reputation: 1, financial: 0 }, 'Zorgvuldig, maar security-actie mag niet stilvallen.'),
        ],
      },
      {
        id: 'avg',
        title: 'De AVG-klok',
        tbkTags: ['Compliance', 'Klantcommunicatie'],
        situation: 'Er is waarschijnlijk sprake van een datalek met persoonsgegevens.',
        question: 'Hoe ga je om met melden?',
        choices: [
          choice('A', 'Melden met onzekerheid', 'Meld bij de AP met wat bekend is en vul later aan.', q.best, 'lesson', { proces: 2 }, { reputation: 0, financial: 0, operation: 0 }, 'De wettelijke klok wordt serieus genomen.'),
          choice('B', 'Wachten op perfect rapport', 'Meld pas als alle forensische details rond zijn.', q.risky, 'lesson', { proces: 2 }, { reputation: 2, financial: 2, operation: 0 }, 'Volledigheid kan te laat komen.'),
          choice('C', 'Klanten eerst, AP later', 'Informeer klanten direct en meld daarna formeel.', q.acceptable, 'lesson', { proces: 1, mens: 1 }, { reputation: 1, financial: 0, operation: 0 }, 'Transparant, maar volgorde en feiten moeten strak worden bewaakt.'),
        ],
      },
      {
        id: 'lesson',
        title: 'Structurele maatregel',
        tbkTags: ['Least privilege', 'Logging'],
        situation: 'De oorzaak blijkt te ruime leverancierstoegang.',
        question: 'Wat voorkomt herhaling het best?',
        choices: [
          choice('A', 'Least privilege en alerts', 'Beperk externe toegang strikt en monitor bulkacties automatisch.', q.best, 'end_scenario', { proces: 2, tech: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Bron, detectie en controle worden gecombineerd.'),
          choice('B', 'Alleen contractboetes', 'Maak leveranciers financieel aansprakelijk.', q.acceptable, 'end_scenario', { proces: 1 }, { operation: 0, reputation: 0, financial: 0 }, 'Regelt gevolgen, maar voorkomt export niet.'),
          choice('C', 'Alleen PR-plan', 'Maak betere klantcommunicatie voor datalekken.', q.risky, 'end_scenario', { proces: 1, mens: 1 }, { reputation: 1, financial: 0, operation: 0 }, 'Nuttig na afloop, te laat als primaire maatregel.'),
        ],
      },
    ],
  },
  {
    id: 'pathe',
    title: 'Pathe CEO-fraude',
    year: '2018',
    sector: 'Entertainment / Finance process',
    role: 'CFO Nederland',
    cia: ['Integrity'],
    category: ['mens', 'proces'],
    tbkLens: 'Interne controle',
    accent: '#9333ea',
    image: imageManifest.pathe,
    sources: ['NOS', 'Accountant.nl', 'Vonnis Amsterdam'],
    intro: [
      'Een overtuigende mail van het hoofdkantoor vraagt om een geheime spoedbetaling. Het domein lijkt te kloppen, maar wijkt subtiel af.',
      'Dit scenario draait om integrity: informatie lijkt betrouwbaar, maar is vervalst. Besluitvorming en betalingsprocessen worden aangevallen.',
    ],
    impactStats: [
      { value: '19.2M', label: 'euro schade' },
      { value: 'BEC', label: 'business email compromise' },
      { value: '4-ogen', label: 'interne controle' },
    ],
    nodes: [
      {
        id: 'start',
        title: 'De eerste betaling',
        tbkTags: ['Interne controle', 'Social engineering'],
        situation: 'De mail vraagt geheimhouding en verwijst naar een overname. Het afzenderdomein wijkt een woord af.',
        question: 'Wat doe je voor betaling?',
        choices: [
          choice('A', 'Tweede kanaal', 'Bel het hoofdkantoor via een bekend officieel nummer.', q.best, 'discover', { mens: 1, proces: 2 }, { operation: 0, reputation: 0, financial: 0 }, 'Fraude wordt ontdekt voordat geld vertrekt.'),
          choice('B', 'Betalen', 'Betaal omdat de vraag urgent en vertrouwelijk is.', q.risky, 'second', { mens: 2, proces: 2 }, { financial: 3, reputation: 1, operation: 0 }, 'De eerste betaling verdwijnt en de fraudeur komt terug.'),
          choice('C', 'Mail terug', 'Vraag extra informatie via dezelfde mailthread.', q.acceptable, 'second', { mens: 1, proces: 1 }, { financial: 1, reputation: 0, operation: 0 }, 'Je zoekt bewijs, maar bij de verkeerde partij.'),
        ],
      },
      {
        id: 'discover',
        title: 'Fraude ontdekt',
        tbkTags: ['Incidentmelding', 'Governance'],
        situation: 'Het hoofdkantoor weet nergens van. Er is nog geen financiele schade.',
        question: 'Wat is de juiste vervolgstap?',
        choices: [
          choice('A', 'Melden en vastleggen', 'Informeer bestuur, bank en politie; bewaar bewijs.', q.best, 'lesson', { proces: 1 }, { financial: 0, reputation: 0, operation: 0 }, 'Snel melden helpt detectie en voorkomt vervolgschade.'),
          choice('B', 'Stil intern uitzoeken', 'Onderzoek eerst zelf wat er gebeurd is.', q.acceptable, 'lesson', { proces: 1 }, { operation: 1, reputation: 0, financial: 0 }, 'Begrijpelijk, maar waarschuwingen komen later.'),
        ],
      },
      {
        id: 'second',
        title: 'De tweede mail',
        tbkTags: ['Tijdsdruk', 'Betalingsmandaat'],
        situation: 'Na de eerste betaling komt een groter verzoek. De psychologische druk neemt toe.',
        question: 'Wat doorbreekt de fraude?',
        choices: [
          choice('A', 'Stop en bel', 'Weiger betaling tot verificatie via officieel kanaal is gelukt.', q.best, 'lesson', { mens: 1, proces: 2 }, { financial: 0, reputation: 0, operation: 0 }, 'De schade stopt en het patroon wordt zichtbaar.'),
          choice('B', 'Doorgaan', 'Betaal omdat stoppen vreemd voelt na de eerste betaling.', q.risky, 'lesson', { mens: 2, proces: 2 }, { financial: 3, reputation: 2, operation: 0 }, 'Sunk cost-denken vergroot de schade.'),
          choice('C', 'Videobel vragen', 'Vraag de CEO om mondelinge bevestiging.', q.acceptable, 'lesson', { mens: 1, proces: 1 }, { financial: 1, reputation: 0, operation: 0 }, 'Een goed signaal, maar alleen veilig als je het kanaal zelf initieert.'),
        ],
      },
      {
        id: 'lesson',
        title: 'Structurele controle',
        tbkTags: ['Interne controle', 'Governance'],
        situation: 'De les is niet dat iemand dom was, maar dat het proces druk niet opving.',
        question: 'Welke maatregel hoort bovenaan?',
        choices: [
          choice('A', 'Vierogen plus verificatie', 'Betalingen boven grensbedrag vereisen twee personen en tweede kanaal.', q.best, 'end_scenario', { proces: 2, mens: 1 }, { financial: 0, reputation: 0, operation: 0 }, 'Een vervalste mail is nooit genoeg.'),
          choice('B', 'Alleen bewustwording', 'Train finance-medewerkers op CEO-fraude.', q.acceptable, 'end_scenario', { mens: 1, proces: 1 }, { financial: 0, reputation: 0, operation: 0 }, 'Nodig, maar zonder procescontrole blijft een fout mogelijk rampzalig.'),
          choice('C', 'Alleen e-mailfilter', 'Gebruik DMARC/SPF en filtering.', q.acceptable, 'end_scenario', { tech: 1, proces: 0 }, { financial: 0, reputation: 0, operation: 0 }, 'Sterk technisch vangnet, maar niet genoeg als enige controle.'),
        ],
      },
    ],
  },
]
